"""M7 orchestrator: `uv run python -m src.report.run`.

Runs every robustness stress against the frozen M5 configuration and emits
reports/m7_robustness.md plus figures. The companion hand-written failure
analysis lives in reports/m7_failure_analysis.md.
"""

from __future__ import annotations

import logging
from pathlib import Path

import matplotlib

matplotlib.use("Agg")  # headless: this module only writes files, never opens windows
import matplotlib.pyplot as plt
import pandas as pd

from src.config import Config, load_config
from src.db import connect
from src.backtest.engine import portfolio_curve
from src.backtest.funding import funding_rate_per_bar
from src.pairs.data import load_close_panel, train_cutoff
from src.paths import plot_dir, report_path
from src.report.robustness import (
    cost_stress,
    grid_train_vs_test,
    leave_one_pair_out,
    regime_slices,
    rolling_eg,
)
from src.validate.grid import spread_cache
from src.validate.run import FULL_HISTORY_END, static_split

log = logging.getLogger(__name__)

REPO_ROOT = Path(__file__).resolve().parents[2]


def plot_sensitivity(table: pd.DataFrame, chosen: dict, rank_corr: float, cfg: Config) -> Path:
    fig, ax = plt.subplots(figsize=(8, 6))
    ax.scatter(table["train_sharpe"], table["test_sharpe"], s=18, alpha=0.7)
    hit = table[
        (table["delta"] == chosen["delta"])
        & (table["zscore_window_bars"] == chosen["zscore_window_bars"])
        & (table["entry_z"] == chosen["entry_z"])
        & (table["exit_z"] == chosen["exit_z"])
        & (table["stop_z"] == chosen["stop_z"])
    ]
    ax.scatter(hit["train_sharpe"], hit["test_sharpe"], s=90, marker="*", color="red",
               label="chosen at M5", zorder=3)
    ax.axhline(0, color="grey", lw=0.6)
    ax.axvline(0, color="grey", lw=0.6)
    ax.set_xlabel("train Sharpe (tuning window)")
    ax.set_ylabel("test Sharpe (untouched)")
    ax.set_title(f"all 72 grid configs, train vs test (Spearman rank corr {rank_corr:+.2f})")
    ax.legend(loc="best", fontsize=8)
    fig.tight_layout()
    out_dir = plot_dir(cfg, "m7")
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / "grid_train_vs_test.png"
    fig.savefig(path, dpi=120)
    plt.close(fig)
    return path


def plot_rolling_eg(eg: pd.DataFrame, cfg: Config) -> Path:
    fig, ax = plt.subplots(figsize=(12, 5))
    for pair, group in eg.groupby("pair"):
        ax.plot(group["window_end"], group["eg_p_max"], label=pair, lw=1.0)
    ax.axhline(0.05, color="red", ls="--", lw=0.8, label="p = 0.05")
    ax.set_ylabel("rolling 1y EG p-value (worst direction)")
    ax.set_title("did the cointegration persist? (lower = stronger)")
    ax.legend(loc="best", fontsize=8)
    fig.tight_layout()
    out_dir = plot_dir(cfg, "m7")
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / "rolling_eg.png"
    fig.savefig(path, dpi=120)
    plt.close(fig)
    return path


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
    cfg = load_config()
    rob = cfg.robustness

    with connect(cfg.db) as conn:
        # Universe + aux so the regime factor column (e.g. SPY) exists in the panel.
        panel = load_close_panel(
            conn, cfg, end=FULL_HISTORY_END, symbols=cfg.data.universe + cfg.data.aux
        )
        open_panel = (
            load_close_panel(conn, cfg, end=FULL_HISTORY_END, field="open")
            if cfg.backtest.fill_at_next_open
            else None
        )
        funding = {
            s: funding_rate_per_bar(conn, cfg, s, FULL_HISTORY_END) for s in cfg.data.universe
        }

    params, _, _, _, _, results = static_split(panel, funding, cfg, open_panel)
    cutoff = pd.Timestamp(train_cutoff(cfg))
    book = list(cfg.signals.book)
    cache = spread_cache(
        panel, book, cfg.validation.grid.kalman_delta, cfg.pairs.kalman.burn_in_bars
    )

    costs = cost_stress(panel, book, params, cache, funding, cfg, cutoff, open_panel)
    log.info("cost stress:\n%s", costs)
    sens, rank_corr = grid_train_vs_test(panel, book, cache, funding, cfg, cutoff, open_panel)
    log.info("grid train-vs-test rank corr: %+.2f", rank_corr)
    loo = leave_one_pair_out(results, cutoff, cfg.data.interval)
    port_test_net = portfolio_curve(results)["net"]
    factor_name = rob.factor_symbol.removesuffix("USDT")  # 'BTCUSDT' -> 'BTC'; 'SPY' -> 'SPY'
    regimes = regime_slices(
        port_test_net.loc[port_test_net.index >= cutoff], panel[rob.factor_symbol],
        rob.regime_window_bars, cfg.data.interval, factor_name,
    )
    eg = rolling_eg(panel, book, rob.rolling_eg_window_bars, rob.rolling_eg_step_bars)
    eg_pass = eg.groupby("pair")["eg_p_max"].agg(["min", "median", lambda s: (s < 0.05).mean()])
    eg_pass.columns = ["min_p", "median_p", "frac_windows_passing"]

    lines = [
        "# M7 robustness — stress tables (frozen M5 config, test window)",
        "",
        "> Auto-generated by `src/report/run.py` — do not edit by hand. The honest",
        "> failure write-up lives in `reports/m7_failure_analysis.md`.",
        "",
        "All stresses are post-hoc diagnostics; nothing here fed back into tuning.",
        "",
        "## Cost stress (does the edge survive double fees?)",
        "",
        "| fee+slip multiplier | test net | test Sharpe |",
        "|---|---|---|",
        *[
            f"| {r.cost_multiplier:g}x | {r.net * 100:+.2f}% | {r.sharpe:+.2f} |"
            for r in costs.itertuples()
        ],
        "",
        "## Parameter sensitivity (was the grid choice skill or luck?)",
        "",
        f"- Spearman rank correlation between train and test Sharpe across all "
        f"{len(sens)} configs: **{rank_corr:+.2f}** "
        "(near zero = the tuning ranking carried little out-of-sample information).",
        f"- Test-Sharpe range across the grid: {sens['test_sharpe'].min():+.2f} to "
        f"{sens['test_sharpe'].max():+.2f}; "
        f"{(sens['test_sharpe'] > 0).mean() * 100:.0f}% of configs were positive OOS.",
        f"- Scatter: `{plot_dir(cfg, 'm7').relative_to(REPO_ROOT)}/grid_train_vs_test.png` "
        "(chosen config starred).",
        "",
        "## Leave-one-pair-out (how much is one pair's doing?)",
        "",
        "| book without | test net | test Sharpe |",
        "|---|---|---|",
        *[
            f"| {r.without} | {r.net * 100:+.2f}% | {r.sharpe:+.2f} |"
            for r in loo.itertuples()
        ],
        "",
        f"## Market-regime slices (test window, trailing {factor_name} labels)",
        "",
        "| regime | bars | net | Sharpe |",
        "|---|---|---|---|",
        *[
            f"| {r.regime} | {r.bars} | {r.net * 100:+.2f}% | {r.sharpe:+.2f} |"
            for r in regimes.itertuples()
        ],
        "",
        "## Rolling cointegration (did the pairs decohere?)",
        "",
        "| pair | min p | median p | % of 1y windows passing 0.05 |",
        "|---|---|---|---|",
        *[
            f"| {pair} | {row.min_p:.3f} | {row.median_p:.3f} "
            f"| {row.frac_windows_passing * 100:.0f}% |"
            for pair, row in eg_pass.iterrows()
        ],
        "",
        f"- Time series: `{plot_dir(cfg, 'm7').relative_to(REPO_ROOT)}/rolling_eg.png`.",
    ]
    out = report_path(cfg, "m7_robustness.md")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n")
    log.info("report written to %s", out)
    log.info("plot: %s", plot_sensitivity(sens, params.__dict__, rank_corr, cfg))
    log.info("plot: %s", plot_rolling_eg(eg, cfg))


if __name__ == "__main__":
    main()
