"""M5 orchestrator: `uv run python -m src.validate.run`.

Two experiments, one report:

  A. STATIC SPLIT — tune the pre-declared grid on the training window (fixed
     M3 book), freeze the winner, run it continuously over the full history,
     and split the PnL at train_end. The in-sample vs out-of-sample gap this
     produces is the project's headline number.

  B. WALK-FORWARD — re-screen pairs and re-tune the grid on a rolling 2y
     window, trade the next quarter untouched, step, stitch. Validates the
     pipeline rather than one parameter choice.

This module is the ONE place that deliberately reads past train_end.
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from pathlib import Path

import matplotlib

matplotlib.use("Agg")  # headless: this module only writes files, never opens windows
import matplotlib.pyplot as plt
import pandas as pd

from src.config import Config, load_config
from src.db import connect
from src.backtest.engine import portfolio_curve
from src.backtest.funding import funding_rate_per_bar
from src.metrics.core import ann_sharpe, summarize
from src.pairs.data import load_close_panel, train_cutoff
from src.validate.grid import ParamSet, grid_search, run_params, spread_cache
from src.validate.walkforward import Fold, run_walkforward

log = logging.getLogger(__name__)

REPO_ROOT = Path(__file__).resolve().parents[2]
REPORT_PATH = REPO_ROOT / "reports" / "m5_validation.md"
PLOT_DIR = REPO_ROOT / "data" / "plots" / "m5"
# Per-bar walk-forward OOS series, persisted (gitignored) so M6+ can consume it
# without re-running ~45 min of per-fold screening.
OOS_CSV = REPO_ROOT / "data" / "m5_walkforward_oos.csv"

# Explicit "give me everything" end for the two M5 evaluations — the deliberate,
# documented crossing of train_end that the rest of the codebase must never do.
FULL_HISTORY_END = datetime(2100, 1, 1, tzinfo=timezone.utc)


def static_split(panel: pd.DataFrame, funding: dict[str, pd.Series], cfg: Config):
    """Experiment A. Returns (best ParamSet, grid table, train stats, test stats,
    portfolio frame over the full span, per-pair result frames)."""
    cutoff = pd.Timestamp(train_cutoff(cfg))
    book = list(cfg.signals.book)
    cache = spread_cache(
        panel, book, cfg.validation.grid.kalman_delta, cfg.pairs.kalman.burn_in_bars
    )
    table = grid_search(
        panel, book, cfg.validation.grid, cache, funding, cfg.backtest,
        cfg.data.interval, cfg.validation.min_trades_per_year, end=cutoff,
    )
    eligible = table[table["eligible"]]
    if eligible.empty:
        raise RuntimeError("no grid config met the minimum-trades floor on train")
    best = eligible.iloc[0]
    params = ParamSet(
        delta=float(best["delta"]),
        zscore_window_bars=int(best["zscore_window_bars"]),
        entry_z=float(best["entry_z"]),
        exit_z=float(best["exit_z"]),
        stop_z=float(best["stop_z"]),
    )
    # Frozen params, continuous run over the whole history (a live desk crossing
    # Jan 1 does not flatten its book), PnL split at the boundary.
    results = run_params(panel, book, params, cache, funding, cfg.backtest)
    port = portfolio_curve(results)
    train_stats = summarize(port.loc[port.index < cutoff], cfg.data.interval)
    test_stats = summarize(port.loc[port.index >= cutoff], cfg.data.interval)
    return params, table, train_stats, test_stats, port, results


def stats_row(name: str, s: dict) -> str:
    return (
        f"| {name} | {s['net'] * 100:+.2f}% | {s['gross'] * 100:+.2f}% "
        f"| {s['costs'] * 100:.2f}% | {s['sharpe']:+.2f} | {s['max_dd'] * 100:+.2f}% "
        f"| {s['bars']} |"
    )


def write_report(
    cfg: Config,
    params: ParamSet,
    table: pd.DataFrame,
    train_stats: dict,
    test_stats: dict,
    oos: pd.Series,
    folds: list[Fold],
) -> Path:
    n_eligible = int(table["eligible"].sum())
    active = [f for f in folds if f.book]
    lines = [
        "# M5 validation — the out-of-sample numbers",
        "",
        "> Auto-generated by `src/validate/run.py` — do not edit by hand. Interpretation",
        "> lives in `reports/m5_validation_notes.md`.",
        "",
        "## A. Static split — tuned on train, frozen, evaluated on test",
        "",
        f"- Grid: {len(table)} pre-declared configs, {n_eligible} met the "
        f"{cfg.validation.min_trades_per_year}/pair-year trades floor. "
        f"Chosen (by train net Sharpe): `{params}`",
        f"- Split at {cfg.validation.train_end}; book fixed to the M3 pairs.",
        "",
        "| window | net | gross | costs | Sharpe | max DD | bars |",
        "|---|---|---|---|---|---|---|",
        stats_row("train (tuned here)", train_stats),
        stats_row("**test (untouched)**", test_stats),
        "",
        f"**The gap:** train Sharpe {train_stats['sharpe']:+.2f} -> "
        f"test Sharpe {test_stats['sharpe']:+.2f}.",
        "",
        "Top of the grid (train ranking, eligibility floor applied):",
        "",
        "| delta | window | entry | exit | stop | net | Sharpe | trades | eligible |",
        "|---|---|---|---|---|---|---|---|---|",
        *[
            f"| {r.delta:g} | {int(r.zscore_window_bars)} | {r.entry_z} | {r.exit_z} "
            f"| {r.stop_z} | {r.net * 100:+.2f}% | {r.sharpe:+.2f} | {int(r.trades)} "
            f"| {'yes' if r.eligible else 'no'} |"
            for r in table.head(10).itertuples()
        ],
        "",
        "## B. Walk-forward — re-screen + re-tune every quarter",
        "",
        f"- Rolling {cfg.validation.walkforward.train_bars}-bar train, "
        f"{cfg.validation.walkforward.test_bars}-bar test, book re-screened per fold "
        f"(max {cfg.validation.walkforward.max_pairs} pairs), grid re-tuned per fold.",
        f"- {len(folds)} folds, {len(active)} traded, {len(folds) - len(active)} held cash "
        "(no passing pairs / no eligible config — recorded, not hidden).",
        "",
    ]
    if len(oos):
        lines += [
            f"**Stitched out-of-sample: net {float(oos.sum()) * 100:+.2f}% over "
            f"{len(oos)} bars, Sharpe {ann_sharpe(oos, cfg.data.interval):+.2f}.**",
            "",
        ]
    lines += [
        "| fold test start | book | delta | window | entry/exit/stop | train Sharpe "
        "| test net | test Sharpe |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for f in folds:
        if not f.book:
            lines.append(f"| {f.test_start.date()} | — (cash) | | | | | | |")
            continue
        p = f.params
        lines.append(
            f"| {f.test_start.date()} | {', '.join(f'{y}/{x}' for y, x in f.book)} "
            f"| {p.delta:g} | {p.zscore_window_bars} "
            f"| {p.entry_z}/{p.exit_z}/{p.stop_z} | {f.train_sharpe:+.2f} "
            f"| {f.test_net * 100:+.2f}% | {f.test_sharpe:+.2f} |"
        )
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text("\n".join(lines) + "\n")
    return REPORT_PATH


def plot_static(port: pd.DataFrame, cfg: Config) -> Path:
    cutoff = pd.Timestamp(train_cutoff(cfg))
    fig, ax = plt.subplots(figsize=(12, 5))
    ax.plot(port.index, port["net"].cumsum() * 100, label="net", lw=1.1)
    ax.plot(port.index, port["gross"].cumsum() * 100, label="gross", lw=0.8)
    ax.axvline(cutoff, color="red", ls="--", lw=1.0, label="train/test split")
    ax.axhline(0, color="grey", lw=0.6)
    ax.set_ylabel("% of unit capital")
    ax.set_title("static split: tuned config, frozen at the red line")
    ax.legend(loc="best", fontsize=8)
    fig.tight_layout()
    PLOT_DIR.mkdir(parents=True, exist_ok=True)
    path = PLOT_DIR / "static_split.png"
    fig.savefig(path, dpi=120)
    plt.close(fig)
    return path


def plot_walkforward(oos: pd.Series) -> Path:
    fig, ax = plt.subplots(figsize=(12, 5))
    ax.plot(oos.index, oos.cumsum() * 100, lw=1.1)
    ax.axhline(0, color="grey", lw=0.6)
    ax.set_ylabel("% of unit capital")
    ax.set_title("walk-forward: stitched out-of-sample equity (every bar untouched at tune time)")
    fig.tight_layout()
    PLOT_DIR.mkdir(parents=True, exist_ok=True)
    path = PLOT_DIR / "walkforward.png"
    fig.savefig(path, dpi=120)
    plt.close(fig)
    return path


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
    cfg = load_config()

    with connect(cfg.db) as conn:
        panel = load_close_panel(conn, cfg, end=FULL_HISTORY_END)
        funding = {
            s: funding_rate_per_bar(conn, cfg, s, FULL_HISTORY_END) for s in cfg.data.universe
        }
    log.info("full panel: %d bars, %s -> %s", len(panel), panel.index.min(), panel.index.max())

    params, table, train_stats, test_stats, port, _ = static_split(panel, funding, cfg)
    log.info("static: chosen %s", params)
    log.info("static: train %s", {k: round(v, 4) for k, v in train_stats.items()})
    log.info("static: test  %s", {k: round(v, 4) for k, v in test_stats.items()})
    log.info("plot: %s", plot_static(port, cfg))

    oos, folds = run_walkforward(panel, funding, cfg)
    if len(oos):
        oos.rename("net").to_csv(OOS_CSV)
        log.info("walk-forward: net %+.2f%% over %d bars (series -> %s)",
                 oos.sum() * 100, len(oos), OOS_CSV)
        log.info("plot: %s", plot_walkforward(oos))

    log.info("report written to %s", write_report(cfg, params, table, train_stats,
                                                  test_stats, oos, folds))


if __name__ == "__main__":
    main()
