"""M3 orchestrator: `uv run python -m src.signals.run`.

Generates the causal spread / z-score / position series for every book pair on
the TRAINING window, upserts them into `pair_signal`, regenerates the summary
at reports/m3_signals.md, and saves a diagnostic plot per pair.
"""

from __future__ import annotations

import logging
from pathlib import Path

import matplotlib

matplotlib.use("Agg")  # headless: this module only writes files, never opens windows
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import psycopg

from src.config import Config, load_config
from src.db import connect
from src.metrics.core import bars_label
from src.pairs.data import load_close_panel
from src.paths import plot_dir, report_path
from src.signals.rules import cancel_entries_without_positive_beta, positions_from_z
from src.signals.spread import signal_frame

log = logging.getLogger(__name__)

REPO_ROOT = Path(__file__).resolve().parents[2]
SCHEMA_PATH = Path(__file__).resolve().parent / "schema.sql"


def build_pair_signals(panel: pd.DataFrame, leg_y: str, leg_x: str, cfg: Config) -> pd.DataFrame:
    frame = signal_frame(
        panel[leg_y], panel[leg_x], cfg.pairs.kalman, cfg.signals.zscore_window_bars
    )
    frame["position"] = positions_from_z(
        frame["z"], cfg.signals.entry_z, cfg.signals.exit_z, cfg.signals.stop_z
    )
    # Same guard the M5 layer applies (rules.py): a non-positive entry beta means
    # a degenerate "pair" — never traded. A no-op for the crypto book (betas well
    # above zero); equity pairs with small OLS betas (e.g. MA~NVDA ~0.17) can dip
    # negative right after burn-in, which is where this first fired in M10.
    frame["position"] = cancel_entries_without_positive_beta(frame["position"], frame["beta"])
    return frame


def store_signals(
    conn: psycopg.Connection, cfg: Config, leg_y: str, leg_x: str, frame: pd.DataFrame
) -> None:
    with conn.cursor() as cur:
        cur.executemany(
            """
            INSERT INTO pair_signal (exchange, interval, leg_y, leg_x, open_time,
                                     beta, spread, z, position)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT (exchange, interval, leg_y, leg_x, open_time) DO UPDATE SET
                beta = EXCLUDED.beta, spread = EXCLUDED.spread,
                z = EXCLUDED.z, position = EXCLUDED.position
            """,
            [
                (
                    cfg.data.exchange, cfg.data.interval, leg_y, leg_x, t,
                    float(r.beta), float(r.spread),
                    None if np.isnan(r.z) else float(r.z), int(r.position),
                )
                for t, r in frame.iterrows()
            ],
        )
    conn.commit()


def summarize(frame: pd.DataFrame, cfg: Config) -> dict:
    """Trade-level preview stats (no PnL — that is M4's job, with costs)."""
    pos = frame["position"]
    entries = ((pos != 0) & (pos.shift(1, fill_value=0) == 0)).sum()
    exits = ((pos == 0) & (pos.shift(1, fill_value=0) != 0)).sum()
    # Classify each flat transition by the z that caused it: |z| >= stop_z is a stop-out.
    exit_z = frame.loc[(pos == 0) & (pos.shift(1, fill_value=0) != 0), "z"].abs()
    stops = int((exit_z >= cfg.signals.stop_z).sum())
    in_market = pos != 0
    holding = in_market.groupby((~in_market).cumsum()).sum()  # lengths of nonzero runs
    return {
        "bars": len(frame),
        "tradeable_bars": int(frame["z"].notna().sum()),
        "entries": int(entries),
        "mean_exits": int(exits) - stops,
        "stop_outs": stops,
        "open_at_end": int(entries) - int(exits),
        "avg_hold_bars": float(holding[holding > 0].mean()) if entries else 0.0,
        "pct_in_market": 100.0 * float(in_market.mean()),
    }


def write_report(cfg: Config, summaries: dict[str, dict]) -> Path:
    lines = [
        "# M3 signals — trade-level preview (training window)",
        "",
        "> Auto-generated by `src/signals/run.py` — do not edit by hand.",
        "",
        f"- **Window:** training only, up to {cfg.validation.train_end}; no PnL here — "
        "PnL only exists net of costs, which is M4.",
        f"- **Rules:** enter |z| >= {cfg.signals.entry_z}, exit at z = {cfg.signals.exit_z}, "
        f"stop at |z| >= {cfg.signals.stop_z}; z over a {cfg.signals.zscore_window_bars}-bar "
        "rolling window on the Kalman innovation spread; re-arm guard after every flat.",
        "- **Warm-up:** Kalman burn-in + rolling window means the first "
        f"~{cfg.pairs.kalman.burn_in_bars + cfg.signals.zscore_window_bars} bars are untradeable.",
        "",
        "| pair (y ~ x) | tradeable bars | entries | mean exits | stop-outs | open at end "
        "| avg hold | % in market |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for name, s in summaries.items():
        lines.append(
            f"| {name} | {s['tradeable_bars']} | {s['entries']} | {s['mean_exits']} "
            f"| {s['stop_outs']} | {s['open_at_end']} "
            f"| {bars_label(s['avg_hold_bars'], cfg.data.interval)} "
            f"| {s['pct_in_market']:.1f}% |"
        )
    out = report_path(cfg, "m3_signals.md")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n")
    return out


def plot_signals(frame: pd.DataFrame, leg_y: str, leg_x: str, cfg: Config) -> Path:
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12, 7), sharex=True)
    ax1.plot(frame.index, frame["z"], lw=0.5)
    for level, style in [(0, "-"), (cfg.signals.entry_z, "--"), (-cfg.signals.entry_z, "--"),
                         (cfg.signals.stop_z, ":"), (-cfg.signals.stop_z, ":")]:
        ax1.axhline(level, color="grey", ls=style, lw=0.8)
    ax1.set_title(f"{leg_y} ~ {leg_x}: rolling z of Kalman spread "
                  f"(entry ±{cfg.signals.entry_z}, stop ±{cfg.signals.stop_z})")
    ax2.fill_between(frame.index, frame["position"], step="post", alpha=0.6)
    ax2.set_yticks([-1, 0, 1])
    ax2.set_title("spread position (+1 long / -1 short)")
    fig.tight_layout()

    out_dir = plot_dir(cfg, "m3")
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"{leg_y}_{leg_x}.png"
    fig.savefig(path, dpi=120)
    plt.close(fig)
    return path


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
    cfg = load_config()

    with connect(cfg.db) as conn:
        conn.execute(SCHEMA_PATH.read_text())
        conn.commit()
        panel = load_close_panel(conn, cfg)  # training window only by default

        summaries: dict[str, dict] = {}
        for leg_y, leg_x in cfg.signals.book:
            frame = build_pair_signals(panel, leg_y, leg_x, cfg)
            store_signals(conn, cfg, leg_y, leg_x, frame)
            summaries[f"{leg_y} ~ {leg_x}"] = summarize(frame, cfg)
            log.info("plot written to %s", plot_signals(frame, leg_y, leg_x, cfg))
            log.info("%s ~ %s: %s", leg_y, leg_x, summaries[f"{leg_y} ~ {leg_x}"])

    log.info("report written to %s", write_report(cfg, summaries))


if __name__ == "__main__":
    main()
