"""Generates data_provenance.md from what is ACTUALLY in the database.

The provenance doc is regenerated (not hand-maintained) so it can never drift
from the data: source, granularity, per-symbol coverage, and known gaps all come
straight from Postgres queries.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

import psycopg

from src.config import REPO_ROOT, Config
from src.ingest.binance import BASE_URL, INTERVAL_MS

HEADER = """\
# Data Provenance

> Auto-generated by `src/ingest/provenance.py` on every ingestion run — do not edit by hand.

- **Source:** Binance USDT-M perpetual futures public REST API (`{base_url}`)
- **Endpoints:** `/fapi/v1/klines` (OHLCV), `/fapi/v1/fundingRate` (realized 8-hourly funding),
  `/fapi/v1/premiumIndexKlines` (perp-vs-index premium, our basis series),
  `/fapi/v1/exchangeInfo` (symbol onboard dates)
- **Granularity:** `{interval}` bars; funding stored as ACTUAL exchange events — predominantly
  8-hourly, but Binance varies the cadence under stress (e.g. SOLUSDT funded ~2-hourly during
  the Nov-2022 FTX collapse), so downstream code must never assume a fixed funding grid
- **Configured range:** {start_date} → {end_str} (UTC). Symbols listed later start at listing.
- **Gap policy:** interior gaps are recorded below and in the `data_gaps` table — never forward-filled.
- **Survivorship note:** `exchangeInfo` only returns symbols that still exist today, so the
  universe (fixed in `config.yaml`) cannot include coins delisted before the first ingestion.
  This is a known limitation, mitigated by freezing the universe up front and never adding
  symbols retroactively based on outcomes.

## Coverage by symbol

| Symbol | Onboarded | First bar | Last bar | Bars stored | Bars expected | Missing | Funding events |
|--------|-----------|-----------|----------|-------------|---------------|---------|----------------|
"""


def write_provenance(conn: psycopg.Connection, cfg: Config) -> Path:
    interval = cfg.data.interval
    step_ms = INTERVAL_MS[interval]
    exchange = cfg.data.exchange
    end_str = cfg.data.end_date or f"{datetime.now(timezone.utc):%Y-%m-%d %H:%M} (open-ended)"

    lines = [
        HEADER.format(
            base_url=BASE_URL,
            interval=interval,
            start_date=cfg.data.start_date,
            end_str=end_str,
        )
    ]

    gap_rows_all: list[str] = []
    with conn.cursor() as cur:
        for symbol in cfg.data.universe:
            cur.execute(
                "SELECT onboard_date FROM symbols WHERE exchange=%s AND symbol=%s",
                (exchange, symbol),
            )
            row = cur.fetchone()
            onboard = f"{row[0]:%Y-%m-%d}" if row and row[0] else "?"

            cur.execute(
                """
                SELECT MIN(open_time), MAX(open_time), COUNT(*) FROM ohlcv
                WHERE exchange=%s AND market='perp' AND symbol=%s AND interval=%s
                """,
                (exchange, symbol, interval),
            )
            first, last, n = cur.fetchone()
            if n == 0:
                lines.append(f"| {symbol} | {onboard} | — | — | 0 | — | — | 0 |\n")
                continue
            expected = int((last - first).total_seconds() * 1000 / step_ms) + 1
            missing = expected - n

            cur.execute(
                "SELECT COUNT(*) FROM funding WHERE exchange=%s AND symbol=%s",
                (exchange, symbol),
            )
            n_funding = cur.fetchone()[0]

            lines.append(
                f"| {symbol} | {onboard} | {first:%Y-%m-%d %H:%M} | {last:%Y-%m-%d %H:%M} "
                f"| {n} | {expected} | {missing} | {n_funding} |\n"
            )

            cur.execute(
                """
                SELECT gap_start, gap_end, n_missing FROM data_gaps
                WHERE exchange=%s AND symbol=%s AND interval=%s ORDER BY gap_start
                """,
                (exchange, symbol, interval),
            )
            for gap_start, gap_end, n_missing in cur.fetchall():
                gap_rows_all.append(
                    f"| {symbol} | {gap_start:%Y-%m-%d %H:%M} | {gap_end:%Y-%m-%d %H:%M} | {n_missing} |\n"
                )

    lines.append("\n## Known gaps (interior missing bars)\n\n")
    if gap_rows_all:
        lines.append("| Symbol | Gap start | Gap end | Missing bars |\n")
        lines.append("|--------|-----------|---------|--------------|\n")
        lines.extend(gap_rows_all)
    else:
        lines.append("None detected.\n")

    out = REPO_ROOT / "data_provenance.md"
    out.write_text("".join(lines))
    return out
