"""M2 orchestrator: `uv run python -m src.pairs.run`.

Screens every unordered pair in the universe for cointegration on the TRAINING
window only, upserts results into the `pair_screen` table, regenerates the
ranked table at reports/m2_pair_screen.md, and saves spread + Kalman-beta
diagnostic plots for the passing pairs.
"""

from __future__ import annotations

import logging
from pathlib import Path

import matplotlib

matplotlib.use("Agg")  # headless: this module only writes files, never opens windows
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import psycopg

from src.config import Config, load_config
from src.db import connect
from src.pairs.cointegration import PairScreenResult, ols_hedge, screen_universe
from src.pairs.data import load_close_panel
from src.pairs.kalman import kalman_hedge

log = logging.getLogger(__name__)

REPO_ROOT = Path(__file__).resolve().parents[2]
SCHEMA_PATH = Path(__file__).resolve().parent / "schema.sql"
REPORT_PATH = REPO_ROOT / "reports" / "m2_pair_screen.md"
PLOT_DIR = REPO_ROOT / "data" / "plots" / "m2"


def store_results(
    conn: psycopg.Connection, cfg: Config, results: list[PairScreenResult]
) -> None:
    with conn.cursor() as cur:
        for r in results:
            cur.execute(
                """
                INSERT INTO pair_screen (exchange, interval, train_end, leg_y, leg_x,
                    n_bars, alpha, beta, eg_p, eg_p_reverse, eg_p_max,
                    half_life_bars, ret_corr, passed)
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                ON CONFLICT (exchange, interval, train_end, leg_y, leg_x) DO UPDATE SET
                    n_bars = EXCLUDED.n_bars, alpha = EXCLUDED.alpha,
                    beta = EXCLUDED.beta, eg_p = EXCLUDED.eg_p,
                    eg_p_reverse = EXCLUDED.eg_p_reverse, eg_p_max = EXCLUDED.eg_p_max,
                    half_life_bars = EXCLUDED.half_life_bars,
                    ret_corr = EXCLUDED.ret_corr, passed = EXCLUDED.passed,
                    created_at = now()
                """,
                (
                    cfg.data.exchange, cfg.data.interval, cfg.validation.train_end,
                    r.leg_y, r.leg_x, r.n_bars, r.alpha, r.beta,
                    r.eg_p, r.eg_p_reverse, r.eg_p_max, r.half_life_bars,
                    r.ret_corr, r.passed,
                ),
            )
    conn.commit()


def write_report(cfg: Config, results: list[PairScreenResult]) -> Path:
    n_passed = sum(r.passed for r in results)
    lines = [
        "# M2 pair screen — ranked cointegration table",
        "",
        "> Auto-generated by `src/pairs/run.py` — do not edit by hand. Analysis notes",
        "> live in `reports/m2_pair_notes.md`.",
        "",
        f"- **Window:** training data only, up to and including {cfg.validation.train_end} "
        "(the test period stays untouched until M5)",
        f"- **Method:** Engle-Granger on log perp closes, screened on the WORSE p-value of "
        f"the two regression directions; pass = eg_p_max < {cfg.pairs.adf_alpha} AND half-life "
        f"in [{cfg.pairs.half_life_min_bars:.0f}, {cfg.pairs.half_life_max_bars:.0f}] bars "
        f"({cfg.data.interval} bars)",
        f"- **Multiple-testing caveat:** {len(results)} pairs tested at "
        f"alpha={cfg.pairs.adf_alpha} -> ~{len(results) * cfg.pairs.adf_alpha:.1f} false "
        "positives expected by chance. The screen is a candidate filter, not proof of edge; "
        "the real arbiter is out-of-sample performance in M5.",
        f"- **Result: {n_passed} of {len(results)} pairs pass.**",
        "",
        "| # | pair (y ~ x) | bars | beta | EG p (worst dir) | half-life | ret corr | passed |",
        "|---|--------------|------|------|------------------|-----------|----------|--------|",
    ]
    for i, r in enumerate(results, 1):
        hl = f"{r.half_life_bars:.0f}h (~{r.half_life_bars / 24:.1f}d)" if r.half_life_bars else "none"
        lines.append(
            f"| {i} | {r.leg_y} ~ {r.leg_x} | {r.n_bars} | {r.beta:.3f} "
            f"| {r.eg_p_max:.4f} | {hl} | {r.ret_corr:.2f} "
            f"| {'**yes**' if r.passed else 'no'} |"
        )
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text("\n".join(lines) + "\n")
    return REPORT_PATH


def plot_pair(panel: pd.DataFrame, r: PairScreenResult, cfg: Config) -> Path:
    """Two diagnostics per passing pair: the OLS spread, and Kalman vs rolling-OLS beta."""
    joint = panel[[r.leg_y, r.leg_x]].dropna()
    y, x = np.log(joint[r.leg_y]), np.log(joint[r.leg_x])
    _, _, spread = ols_hedge(y, x)
    kalman = kalman_hedge(y, x, cfg.pairs.kalman)

    # 30d rolling OLS beta as a model-free sanity reference for the Kalman path.
    window = 720
    rolling_beta = (
        y.rolling(window).cov(x) / x.rolling(window).var()
    )

    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12, 7), sharex=True)
    ax1.plot(spread.index, spread, lw=0.5)
    for k in (-2, 0, 2):
        ax1.axhline(spread.mean() + k * spread.std(), color="grey", ls="--", lw=0.8)
    ax1.set_title(
        f"{r.leg_y} ~ {r.leg_x}: OLS log-spread (train), "
        f"EG p={r.eg_p_max:.4f}, half-life~{r.half_life_bars / 24:.1f}d"
    )
    ax2.plot(kalman.index, kalman["beta"], label="Kalman beta (filtered)", lw=1.0)
    ax2.plot(rolling_beta.index, rolling_beta, label="30d rolling OLS beta", lw=0.8, alpha=0.7)
    ax2.axhline(r.beta, color="grey", ls="--", lw=0.8, label="full-train OLS beta")
    ax2.set_title("time-varying hedge ratio")
    ax2.legend(loc="best", fontsize=8)
    fig.tight_layout()

    PLOT_DIR.mkdir(parents=True, exist_ok=True)
    path = PLOT_DIR / f"{r.leg_y}_{r.leg_x}.png"
    fig.savefig(path, dpi=120)
    plt.close(fig)
    return path


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
    cfg = load_config()

    with connect(cfg.db) as conn:
        conn.execute(SCHEMA_PATH.read_text())
        conn.commit()
        panel = load_close_panel(conn, cfg)  # training window only by default
        log.info(
            "panel loaded: %d bars x %d symbols, %s -> %s (train_end=%s)",
            len(panel), panel.shape[1], panel.index.min(), panel.index.max(),
            cfg.validation.train_end,
        )

        results = screen_universe(panel, cfg.pairs)
        store_results(conn, cfg, results)

    n_passed = sum(r.passed for r in results)
    log.info("screened %d pairs, %d passed", len(results), n_passed)
    log.info("report written to %s", write_report(cfg, results))
    for r in results:
        if r.passed:
            log.info("plot written to %s", plot_pair(panel, r, cfg))


if __name__ == "__main__":
    main()
