"""M4 orchestrator: `uv run python -m src.backtest.run`.

Backtests the book on the TRAINING window with real frictions (taker fee,
slippage, actual funding events), upserts per-bar results into `pair_backtest`,
regenerates reports/m4_backtest.md, and saves equity-curve plots.
"""

from __future__ import annotations

import logging
from pathlib import Path

import matplotlib

matplotlib.use("Agg")  # headless: this module only writes files, never opens windows
import matplotlib.pyplot as plt
import pandas as pd
import psycopg

from src.config import Config, load_config
from src.db import connect
from src.pairs.data import load_close_panel, train_cutoff
from src.backtest.engine import backtest_pair, portfolio_curve
from src.backtest.funding import funding_rate_per_bar

log = logging.getLogger(__name__)

REPO_ROOT = Path(__file__).resolve().parents[2]
SCHEMA_PATH = Path(__file__).resolve().parent / "schema.sql"
REPORT_PATH = REPO_ROOT / "reports" / "m4_backtest.md"
PLOT_DIR = REPO_ROOT / "data" / "plots" / "m4"


def load_signals(
    conn: psycopg.Connection, cfg: Config, leg_y: str, leg_x: str
) -> pd.DataFrame:
    rows = conn.execute(
        """
        SELECT open_time, beta, position FROM pair_signal
        WHERE exchange = %s AND interval = %s AND leg_y = %s AND leg_x = %s
          AND open_time < %s
        ORDER BY open_time
        """,
        (cfg.data.exchange, cfg.data.interval, leg_y, leg_x, train_cutoff(cfg)),
    ).fetchall()
    df = pd.DataFrame(rows, columns=["open_time", "beta", "position"]).set_index("open_time")
    return df.astype({"beta": float, "position": int})


def store_results(
    conn: psycopg.Connection, cfg: Config, leg_y: str, leg_x: str, frame: pd.DataFrame
) -> None:
    with conn.cursor() as cur:
        cur.executemany(
            """
            INSERT INTO pair_backtest (exchange, interval, leg_y, leg_x, open_time,
                                       w_y, w_x, gross, fee, slip, funding, net)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT (exchange, interval, leg_y, leg_x, open_time) DO UPDATE SET
                w_y = EXCLUDED.w_y, w_x = EXCLUDED.w_x, gross = EXCLUDED.gross,
                fee = EXCLUDED.fee, slip = EXCLUDED.slip,
                funding = EXCLUDED.funding, net = EXCLUDED.net
            """,
            [
                (
                    cfg.data.exchange, cfg.data.interval, leg_y, leg_x, t,
                    float(r.w_y), float(r.w_x), float(r.gross), float(r.fee),
                    float(r.slip), float(r.funding), float(r.net),
                )
                for t, r in frame.iterrows()
            ],
        )
    conn.commit()


def totals(frame: pd.DataFrame) -> dict[str, float]:
    out = {c: float(frame[c].sum()) for c in ["gross", "fee", "slip", "funding", "net"]}
    # Defensive reconciliation on real data (the unit tests prove it on synthetic):
    residual = out["net"] - (out["gross"] - out["fee"] - out["slip"] + out["funding"])
    assert abs(residual) < 1e-9, f"PnL decomposition does not reconcile: {residual}"
    return out


def write_report(cfg: Config, pair_totals: dict[str, dict], port: dict) -> Path:
    def row(name: str, t: dict) -> str:
        return (
            f"| {name} | {t['gross'] * 100:+.2f}% | {t['fee'] * 100:.2f}% "
            f"| {t['slip'] * 100:.2f}% | {t['funding'] * 100:+.2f}% | {t['net'] * 100:+.2f}% |"
        )

    lines = [
        "# M4 backtest — training window, net of frictions",
        "",
        "> Auto-generated by `src/backtest/run.py` — do not edit by hand.",
        "",
        f"- **Window:** training only, up to {cfg.validation.train_end}. "
        "All numbers are cumulative arithmetic PnL on unit capital (per pair, and per "
        "1.0 of book capital split equally across pairs for the portfolio).",
        f"- **Frictions:** taker fee {cfg.backtest.taker_fee_bps}bps + slippage "
        f"{cfg.backtest.slippage_bps}bps per unit turnover; funding from ACTUAL stored "
        "events (never an assumed 8h grid).",
        "- **Execution:** decided at bar close, filled next bar open (= prior close in a "
        "24/7 market, priced via slippage); beta frozen at entry.",
        "- Sharpe/drawdown/etc. deliberately deferred to M6 (honest metrics).",
        "",
        "| book unit | gross | fees | slippage | funding | net |",
        "|---|---|---|---|---|---|",
        *[row(name, t) for name, t in pair_totals.items()],
        row("**portfolio**", port),
    ]
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text("\n".join(lines) + "\n")
    return REPORT_PATH


def plot_pair(frame: pd.DataFrame, name: str, fname: str) -> Path:
    fig, ax = plt.subplots(figsize=(12, 5))
    ax.plot(frame.index, frame["gross"].cumsum() * 100, label="gross", lw=0.9)
    ax.plot(frame.index, frame["net"].cumsum() * 100, label="net (after fees+slip+funding)", lw=1.1)
    ax.plot(frame.index, -(frame["fee"] + frame["slip"]).cumsum() * 100,
            label="cumulative trading costs", lw=0.8, ls="--")
    ax.plot(frame.index, frame["funding"].cumsum() * 100, label="cumulative funding", lw=0.8, ls=":")
    ax.axhline(0, color="grey", lw=0.6)
    ax.set_ylabel("% of unit capital")
    ax.set_title(name)
    ax.legend(loc="best", fontsize=8)
    fig.tight_layout()

    PLOT_DIR.mkdir(parents=True, exist_ok=True)
    path = PLOT_DIR / fname
    fig.savefig(path, dpi=120)
    plt.close(fig)
    return path


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
    cfg = load_config()

    with connect(cfg.db) as conn:
        conn.execute(SCHEMA_PATH.read_text())
        conn.commit()
        panel = load_close_panel(conn, cfg)  # training window only by default

        pair_results: dict[str, pd.DataFrame] = {}
        pair_totals: dict[str, dict] = {}
        for leg_y, leg_x in cfg.signals.book:
            sig = load_signals(conn, cfg, leg_y, leg_x)
            frame = backtest_pair(
                close_y=panel[leg_y].reindex(sig.index),
                close_x=panel[leg_x].reindex(sig.index),
                desired=sig["position"],
                beta=sig["beta"],
                funding_y=funding_rate_per_bar(conn, cfg, leg_y, train_cutoff(cfg)),
                funding_x=funding_rate_per_bar(conn, cfg, leg_x, train_cutoff(cfg)),
                cfg=cfg.backtest,
            )
            store_results(conn, cfg, leg_y, leg_x, frame)
            name = f"{leg_y} ~ {leg_x}"
            pair_results[name] = frame
            pair_totals[name] = totals(frame)
            log.info("%s: %s", name, {k: f"{v * 100:+.2f}%" for k, v in pair_totals[name].items()})
            log.info("plot: %s", plot_pair(frame, name, f"{leg_y}_{leg_x}.png"))

    port = portfolio_curve(pair_results)
    port_totals = totals(port)
    log.info("portfolio: %s", {k: f"{v * 100:+.2f}%" for k, v in port_totals.items()})
    log.info("plot: %s", plot_pair(port, "portfolio (equal-weight pairs)", "portfolio.png"))
    log.info("report written to %s", write_report(cfg, pair_totals, port_totals))


if __name__ == "__main__":
    main()
